### PR TITLE
Adds the diag argument 

### PR DESCRIPTION
**Pull request by koheiw**
This PR adds the `diag` argument to `simil()` and `dist()`. When it is `TRUE`, they compute only similarity/distance between corresponding rows and columns in `x` and `y`. This saves a lot of time in some cases.

### CODE REVIEW

**Comment by rcannood** [comment]
I'll take a look on Monday, would that be okay?

(Hooray for github actions!)

**Comment by koheiw** [comment]
Thanks. Looking forward too your comments.

**Comment by rcannood** [comment]
Looks good! 

I _guess_ that if performance is still an issue, you could create a `struct proxy_diag : public Worker`, which would remove a lot of code related to working with tuples & matrices, but it would make maintaining the package more difficult -- that is, making sure that the `proxy_diag` and `proxy_pair` offer the same functionality.

**Comment by rcannood** [comment]
... I don't know why R-CMD-check/windows-latest is failing. I only changed `NEWS.md` and `.Rbuildignore`. I'll trigger a rebuild to see if the problem persists...

**Review by rcannood — APPROVED** [review]

**Comment by rcannood** [comment]
I just ran a `devtools::check_win_devel()` and also got the following [output](https://win-builder.r-project.org/kCXFbs737kx9/00install.out): 

```
D:/Compiler/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -ltbb
D:/Compiler/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -ltbbmalloc
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'proxyC'
* removing 'd:/RCompile/CRANguest/R-devel/lib/proxyC'
```

I see that [RcppParallel](https://cran.r-project.org/web/packages/RcppParallel/index.html) was updated yesterday, maybe this is the reason?

**Comment by koheiw** [comment]
You are probably right that checks are failing on Windows (it still builds) because of the RcppParallel changes. The same error happen on my Windows after update to v5.1.1 from the source. I still do not to how to fix so hoping that Windows binary on CRAN will solve the issue...

**Comment by koheiw** [comment]
Regarding performance, `proxy_pair` is much slower than `proxy_linear` but the small number of pairs when `diag = TRUE` seems outweights the disadvantage. Let's see if we (or users) want to make it even faster.

```r
> mat1 <- rsparsematrix(1000, 1000, 0.01, rand.x = sample.int)
> mat2 <- rsparsematrix(1000, 1000, 0.01, rand.x = sample.int)
> microbenchmark::microbenchmark(
+     diag(simil(mat1, mat2)),
+     diag(simil(mat1, mat2, diag = TRUE))
+ )
Unit: milliseconds
                                 expr        min        lq       mean     median         uq       max neval
              diag(simil(mat1, mat2)) 107.108599 117.91593 151.811298 127.999289 185.834339 325.83526   100
 diag(simil(mat1, mat2, diag = TRUE))   1.865122   2.26054   3.052994   2.424413   2.824056  13.87824   100
```

**Comment by koheiw** [comment]
A bug on RcppParallel on Windows has been confirmed, so let me merge. 

https://github.com/RcppCore/RcppParallel/issues/118
